application: easychip-demo
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(buy|pay|channel|history)
  script: web.app
  secure: always

- url: /(.*\.(js|css|png|txt))
  static_files: static/\1
  upload: static/(.*\.(js|css|png|txt))
  secure: always

- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always

libraries:
- name: pycrypto
  version: "latest"
